name: Build React App (Experiment-8)

on:
  push:
    branches: [main]
    paths: ['react-project/Experiment-8/**']
  pull_request:
    branches: [main]
    paths: ['react-project/Experiment-8/**']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    defaults:
      run:
        working-directory: react-project/Experiment-8
        
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          
      - name: Build Docker Image
        run: docker build -t react-experiment-3-1 .
      
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=$(date +%Y%m%d-%H%M%S)
          docker tag react-experiment-3-1 ${{ secrets.DOCKERHUB_USERNAME }}/react-experiment-3-1:$VERSION
          docker tag react-experiment-3-1 ${{ secrets.DOCKERHUB_USERNAME }}/react-experiment-3-1:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-experiment-3-1:$VERSION
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-experiment-3-1:latest

